services:
  # Backend API service
  - type: web
    name: xidach-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://{username}.github.io/xi-dach-de # Replace {username} with your GitHub username

  # Frontend static site
  - type: web
    name: xidach-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_SERVER_URL
        value: https://xidach-server.onrender.com 